# Generated by Django 2.2.5 on 2019-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(default='hoge', max_length=50),
            preserve_default=False,
        ),
    ]
